{% set name = "stumpy" %}
{% set version = "1.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0b27d019c51097d16eb44f578c4dc18413264e2856a0d3426b81370383dc1182

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=1.17
    - scipy >=1.5
    - numba >=0.54

test:
  requires:
    - setuptools
    - python {{ python_min }}
  imports:
    - stumpy

about:
  home: http://github.com/TDAmeritrade/stumpy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'STUMPY is a powerful and scalable Python library that computes something called a matrix profile, which can then be used for a variety of time series data mining tasks'

  description: |
    STUMPY is a powerful and scalable Python library that computes something called a matrix profile, which can then be used for a variety of time series data mining tasks.
  doc_url: https://github.com/TDAmeritrade/stumpy/blob/master/README.rst
  dev_url: https://github.com/TDAmeritrade/stumpy

extra:
  recipe-maintainers:
    - seanlaw
    - NimaSarajpoor
