{% set name = "stumpy" %}
{% set version = "1.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a2429d1d309e7fe24a2861b59f7a84190263fde1afa87bb8c749b236bfe0515a

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - numpy >=1.15
    - scipy >=1.5
    - numba >=0.48

test:
  requires:
    - setuptools
  imports:
    - stumpy

about:
  home: http://github.com/TDAmeritrade/stumpy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'STUMPY is a powerful and scalable Python library that computes something called a matrix profile, which can then be used for a variety of time series data mining tasks'

  description: |
    STUMPY is a powerful and scalable Python library that computes something called a matrix profile, which can then be used for a variety of time series data mining tasks.
  doc_url: https://github.com/TDAmeritrade/stumpy/blob/master/README.rst
  dev_url: https://github.com/TDAmeritrade/stumpy

extra:
  recipe-maintainers:
    - seanlaw
